version: '3.8'
services:
  mysql:
    image: "mysql:8.0"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: tinyurldb
  redis:
    image: "redis:6.2"
    ports:
      - "6379:6379"